CREATE TABLE [dbo].[Jokes]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
    [Value] NVARCHAR(2000) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL,
    [UpdatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [PK_Jokes]  PRIMARY KEY CLUSTERED ([Id] ASC)
);
