CREATE TABLE [dbo].[Jokes]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
    [IconUrl] NVARCHAR(2048) NULL,
    [Url] NVARCHAR(2048) NULL,
    [Value] NVARCHAR(2000) NOT NULL,
    [CreatedAt] DATETIME2 NULL,
    [UpdatedAt] DATETIME2 NULL,
    CONSTRAINT [PK_Jokes]  PRIMARY KEY CLUSTERED ([Id] ASC)
);
